name: Publish

on: [push, pull_request]

env:
  DENO_DIR: /home/runner/.cache/deno

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno task wasmbuild
      - run: deno fmt --check
      - run: deno lint
      - run: deno test -A

      - run: deno run -A jsr:@david/publish-on-tag@0.2.0
