name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DENO_DIR: /home/runner/.cache/deno

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno task wasmbuild
      - run: deno task test
      - run: deno publish --dry-run
